application: fju-diploma
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /img
  static_dir: img

- url: /files
  static_dir: files

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /locales
  static_dir: locales

- url: /pdf
  static_dir: pdf

- url: /enrollment_step2.html
  static_files: templates/enrollment_step2.html
  upload: templates/enrollment_step2\.html

- url: /enrollment_step3.html
  static_files: enrollment_step3.html
  upload: enrollment_step3\.html

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
